env:
  browser: true
  commonjs: true
  node: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - airbnb
rules:
  array-callback-return: error
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  block-spacing: error
  brace-style: error
  callback-return: error
  camelcase: error
  comma-dangle:
    - error
    - only-multiline
  comma-spacing: error
  comma-style: error
  complexity: warn
  curly: error
  default-case: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  global-require: error
  handle-callback-err: error
  import/newline-after-import: warn
  import/no-extraneous-dependencies: warn
  import/no-mutable-exports: error
  indent:
    - error
    - 2
  max-depth:
    - error
    - 10
  new-cap: off
  newline-per-chained-call: error
  no-class-assign: error
  no-console:
    - error
    - allow:
      - error
  no-constant-condition: error
  no-dupe-class-members: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports: error
  no-empty-function: error
  no-empty-pattern: error
  no-empty: error
  no-extra-boolean-cast: error
  no-func-assign: error
  no-irregular-whitespace: error
  no-lonely-if: error
  no-mixed-requires: error
  no-mixed-spaces-and-tabs: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new-require: error
  no-path-concat: error
  no-process-exit: error
  no-redeclare: error
  no-shadow: error
  no-sync: error
  no-undef: error
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-unexpected-multiline: error
  no-unneeded-ternary: error
  no-unreachable: error
  no-unused-expressions: error
  no-unused-vars: error
  no-useless-call: error
  no-useless-concat: error
  no-warning-comments: warn
  padded-blocks: off
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
  prefer-const: error
  radix: error
  react/jsx-boolean-value:
    - error
    - never
  react/jsx-closing-bracket-location: off
  react/jsx-equals-spacing:
    - error
    - never
  react/jsx-first-prop-new-line:
    - error
    - multiline
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-indent:
    - error
    - 2
  react/jsx-no-bind:
    - error
    - ignoreRefs: true
  react/jsx-no-duplicate-props: error
  react/jsx-no-literals: error
  react/jsx-no-undef: error
  react/jsx-pascal-case: off
  react/jsx-space-before-closing: error
  react/jsx-uses-vars: error
  react/no-deprecated: error
  react/no-did-mount-set-state:
    - error
    - allow-in-func
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-set-state: error
  react/no-unknown-property: error
  react/prefer-stateless-function: error
  react/prop-types:
    - error
    - ignore:
      - dispatch
  react/react-in-jsx-scope: off
  react/require-render-return: error
  react/self-closing-comp: error
  react/sort-comp: error
  react/sort-prop-types:
    - warn
    - ignoreCase: true
  react/wrap-multilines: off
  semi:
    - error
    - never
  sort-imports: off
  sort-vars: warn
  yoda:
    - error
    - always
