import {
  authenticateRequest,
  deauthenticateRequest,
  friendsRequest,
  gameInvite,
  acceptGameInvite,
  declineGameInvite,
  cancelGameInvite,
  broadcastNetworkStatus,
  loadGame,
  fireCannon,
  newGame,
  gamesRequest,
  joinGame,
} from '../../actions'
import {
  AUTHENTICATE_REQUEST,
  DEAUTHENTICATE_REQUEST,
  FRIENDS_REQUEST,
  GAME_INVITE_REQUEST,
  ACCEPT_GAME_INVITE_REQUEST,
  DECLINE_GAME_INVITE_REQUEST,
  CANCEL_GAME_INVITE_REQUEST,
  RECEIVE_FRIEND_NETWORK_STATUS,
  LOAD_GAME_REQUEST,
  FIRE_CANNON_REQUEST,
  NEW_GAME_REQUEST,
  GAMES_REQUEST,
  JOIN_GAME_REQUEST,
} from '../../constants/ActionTypes'

// @TODO perhaps this belongs in a custom middleware
export const actions = {
  [AUTHENTICATE_REQUEST]: authenticateRequest,
  [DEAUTHENTICATE_REQUEST]: deauthenticateRequest,
  [FRIENDS_REQUEST]: friendsRequest,
  [GAME_INVITE_REQUEST]: gameInvite,
  [ACCEPT_GAME_INVITE_REQUEST]: acceptGameInvite,
  [DECLINE_GAME_INVITE_REQUEST]: declineGameInvite,
  [CANCEL_GAME_INVITE_REQUEST]: cancelGameInvite,
  [RECEIVE_FRIEND_NETWORK_STATUS]: broadcastNetworkStatus,
  [LOAD_GAME_REQUEST]: loadGame,
  [FIRE_CANNON_REQUEST]: fireCannon,
  [NEW_GAME_REQUEST]: newGame,
  [GAMES_REQUEST]: gamesRequest,
  [JOIN_GAME_REQUEST]: joinGame,
}
